const assert = require('node:assert/strict');

const storageKeys = require('../src/shared/storage/keys.js');
const searchProtocol = require('../src/shared/search/protocol.js');
const searchEngines = require('../src/shared/search/engines.js');
const searchFavicons = require('../src/shared/search/favicons.js');
const siteSearchProviders = require('../src/shared/search/site-search-providers.js');

function run() {
  assert.equal(
    storageKeys.DEFAULT_SEARCH_ENGINE_STORAGE_KEY,
    '_x_extension_default_search_engine_2024_unique_',
    'default search engine storage key should come from the shared key registry'
  );

  assert.deepEqual(
    storageKeys.REMOVED_AI_SYNC_STORAGE_KEYS,
    ['_x_extension_ai_provider_2026_unique_', '_x_extension_ai_disabled_2026_unique_'],
    'removed AI sync keys should stay centralized'
  );

  assert.equal(
    searchProtocol.normalizeSearchSuggestionsMode('classic'),
    'classic',
    'classic mode should remain stable in the shared protocol'
  );

  assert.equal(
    searchProtocol.normalizeSearchSuggestionsMode('ai'),
    'classic',
    'unknown protocol modes should fall back to classic'
  );

  assert.equal(
    searchEngines.getSearchEngineByHostname('www.baidu.com').id,
    'baidu',
    'hostname lookup should use the shared engine definitions'
  );

  assert.equal(
    searchEngines.buildSearchEngineUrl('bing', 'lumno docs'),
    'https://www.bing.com/search?q=lumno%20docs',
    'shared engine URLs should be built from one source of truth'
  );

  assert.equal(
    searchEngines.isSearchEngineResultUrl('https://www.so.com/s?q=lumno'),
    true,
    'shared engine helpers should recognize search result URLs'
  );

  assert.equal(
    searchFavicons.normalizeFaviconHost('www.my.feishu.cn'),
    'feishu.cn',
    'favicon host normalization should collapse feishu subdomains'
  );

  assert.equal(
    searchFavicons.getGoogleFaviconUrl('www.example.com', { size: 64 }),
    'https://www.google.com/s2/favicons?domain=example.com&sz=64',
    'google favicon URLs should be generated by the shared helper'
  );

  assert.equal(
    searchFavicons.getSiteSearchProviderHost({
      template: 'https://www.zhihu.com/search?q={query}'
    }),
    'zhihu.com',
    'site-search provider hosts should be resolved by the shared helper'
  );

  assert.equal(
    siteSearchProviders.getSiteSearchDisplayName(
      { key: 'zw', name: 'Wikipedia' },
      (messageKey, fallback) => `${messageKey}:${fallback}`,
      '站内'
    ),
    'site_search_name_wikipedia:Wikipedia',
    'builtin provider message mapping should come from the shared helper'
  );

  assert.equal(
    siteSearchProviders.getSiteSearchDisplayName(
      { key: 'custom', name: 'Docs' },
      () => '',
      '站内'
    ),
    'Docs',
    'custom providers should keep their explicit name'
  );
}

run();
console.log('shared search module tests passed');
